insert into category (description) values ('AMERICAN')
insert into category (description) values ('ITALIAN')
insert into category (description) values ('MEXICAN')
insert into category (description) values ('FAST FOOD')
insert into unit_of_measure (description) values ('Teaspoon')
insert into unit_of_measure (description) values ('Tablespoon')
insert into unit_of_measure (description) values ('Cup')
insert into unit_of_measure (description) values ('Pinch')
insert into unit_of_measure (description) values ('Ounce')